### ISSUE TITLE
Wrong cd E:/Programy/Screaming Frog SEO Spider/

### ISSUE THREAD

**Issue by osinthill** [Leszek-Sieminski/screamingFrogR#1]
Hi Leszek,
Thanks for the script ! 
When I try to run the crawl, the cd is going to a wrong directory : 

- cd E:/Programy/Screaming Frog SEO Spider/

instead of : 
cd "C:\Program Files (x86)\Screaming Frog SEO Spider"

How can I change that ?

Error in Rstudio is

```
C:\Users\ntl9M76\Documents>cd E:/Programy/Screaming Frog SEO Spider/
The system cannot find the drive specified.
```

Thanks,
Nicolas

**Comment by osinthill** [comment]
Sorry, just found it in R/sfr_command !

**Comment by Leszek-Sieminski** [comment]
Hi, thanks for the issue! 

You're right, I forgot to include the global enviroment variable. I will fix this.

**Comment by osinthill** [comment]
Great :) Thank you Leszek !

**Comment by Leszek-Sieminski** [comment]
Hi Nicolas! I've fixed this, the path is now received from enviromental variable properly :) Please reinstall the package with devtools::install_github("Leszek-Sieminski/screamingFrogR") to obtain the fixed version.

I'm closing this issue, let me know if if everything works on your computer and please reopen or create a new issue in case of any bugs.

Cheers!

**Comment by osinthill** [comment]
Everything works fine :) Thanks !
Nicolas
